/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_uniluebeck_iti_PopCode_MOEA_NSGA2PopCode */

#ifndef _Included_de_uniluebeck_iti_PopCode_MOEA_NSGA2PopCode
#define _Included_de_uniluebeck_iti_PopCode_MOEA_NSGA2PopCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_uniluebeck_iti_PopCode_MOEA_NSGA2PopCode
 * Method:    LaunchArgos
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_de_uniluebeck_iti_PopCode_MOEA_NSGA2PopCode_LaunchArgos
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
