/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_uniluebeck_iti_PopCode_MOEA_PopCode */

#ifndef _Included_de_uniluebeck_iti_PopCode_MOEA_PopCode
#define _Included_de_uniluebeck_iti_PopCode_MOEA_PopCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_uniluebeck_iti_PopCode_MOEA_PopCode
 * Method:    LaunchArgos
 * Signature: ([IILjava/lang/String;I)D
 */
JNIEXPORT jdouble JNICALL Java_de_uniluebeck_iti_PopCode_MOEA_PopCode_LaunchArgos
  (JNIEnv *, jobject, jintArray, jint, jstring, jint);

/*
 * Class:     de_uniluebeck_iti_PopCode_MOEA_PopCode
 * Method:    InitArgos
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_uniluebeck_iti_PopCode_MOEA_PopCode_InitArgos
  (JNIEnv *, jobject);

/*
 * Class:     de_uniluebeck_iti_PopCode_MOEA_PopCode
 * Method:    DestroyArgos
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_uniluebeck_iti_PopCode_MOEA_PopCode_DestroyArgos
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
